### ISSUE TITLE
Please add support for latest Tailwindcss and Vite

### ISSUE THREAD

**Issue by rpasichnyk** [Lukem121/svelte-vite-tailwind-template#1]
This template is awesome!
I tried updating all packages and got build errors with latest Vite 2.7.x and Tailwindcss 3.0.x

Please have a look when you have time :)

**Comment by alkanna** [comment]
@rpasichnyk use `@sveltejs/vite-plugin-svelte` instead of the plugin used here.

**Comment by Lukem121** [comment]
Updated Vite to 2.8.x and Tailwind to 3.0.x
